# TODO: finish me
Resources:
  AppFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: app.handler 
      # Update the runtime
      Runtime: nodejs20.x
      # Use Arm
      Architectures:
        - x86_64
      # Is this needed?
      Events:
        Testing:
          Type: Api 
          Properties:
            Path: /ping
            Method: get
      # Probably don't want this
      Environment:
        Variables:
          NODE_OPTIONS: --enable-source-maps
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        # Probably want this
        Minify: false
        OutExtension:
          - .js=.mjs
        # May be a newer target
        Target: "es2020"
        # Probably don't want this
        Sourcemap: true
        EntryPoints: 
          - app.ts
        # External:
        #   - "<package-to-exclude>"
